'use client';

import Image from 'next/image';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowRight, CheckCircle2, ChevronRight, Landmark, MapPin, Search, Sparkles, TrendingUp } from 'lucide-react';
import { cityHighlights, properties } from '@/lib/data';
import { PropertyCard } from './property-card';
import { t } from '@/lib/i18n';
import { useRouter } from 'next/navigation';
import { useState } from 'react';

export function HomeExperience({ locale }: { locale: string }) {
  const words = t(locale); const [purpose, setPurpose] = useState<'sale'|'rent'>('sale'); const [query, setQuery] = useState(''); const router = useRouter();
  const submit = (event: React.FormEvent) => { event.preventDefault(); router.push(`/${locale}/properties?purpose=${purpose}${query ? `&q=${encodeURIComponent(query)}` : ''}`); };
  return <main className="overflow-hidden">
    <section className="page-shell pt-6 md:pt-9"><div className="relative min-h-[640px] overflow-hidden rounded-[2rem] bg-navy px-6 py-12 text-white shadow-float md:min-h-[690px] md:px-14 md:py-20"><Image priority src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2000&q=90" alt="Contemporary estate exterior" fill sizes="100vw" className="object-cover object-center opacity-75"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(9,28,36,.92)_0%,rgba(13,42,51,.68)_46%,rgba(12,32,38,.18)_100%)]"/><div className="absolute inset-0 bg-grain opacity-30 mix-blend-overlay"/><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.75}} className="relative z-10 max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-bold tracking-wide text-gold backdrop-blur"><Sparkles size={13}/> LOCAL HOMES, ELEVATED</div><h1 className="mt-7 font-serif text-5xl font-bold leading-[.97] tracking-tight md:text-7xl lg:text-[82px]">{words.find}</h1><p className="mt-7 max-w-xl text-base leading-7 text-white/70 md:text-lg">A calmer, more considered way to buy, rent and list property—built around the places and people that matter to you.</p>
      <form onSubmit={submit} className="mt-10 max-w-3xl rounded-2xl bg-white p-2 shadow-2xl shadow-black/30"><div className="flex flex-wrap items-center gap-1"><div className="flex rounded-xl bg-slate-100 p-1">{(['sale','rent'] as const).map(item=><button type="button" onClick={()=>setPurpose(item)} key={item} className={`rounded-lg px-4 py-2 text-xs font-bold transition ${purpose===item ? 'bg-white text-ink shadow-sm' : 'text-slate-500'}`}>{item === 'sale' ? words.sale : words.rent}</button>)}</div><div className="hidden h-8 border-l border-slate-200 sm:block"/><label className="flex min-w-[200px] flex-1 items-center gap-2 px-2"><MapPin size={18} className="text-gold"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={words.search} className="w-full bg-transparent py-2 text-sm text-ink outline-none placeholder:text-slate-400"/></label><button className="gold-button rounded-xl px-5"><Search size={17}/><span>Search</span></button></div></form>
      <div className="mt-6 flex flex-wrap gap-2 text-xs text-white/75"><span className="py-1">Popular:</span>{['Golf Course Road','DLF Phase 4','Sector 43'].map((place)=><button onClick={()=>setQuery(place)} className="rounded-full border border-white/20 px-3 py-1 transition hover:bg-white/10" key={place}>{place}</button>)}</div></motion.div>
      <div className="absolute bottom-7 left-6 right-6 z-10 hidden grid-cols-3 gap-3 border-t border-white/15 pt-5 md:left-14 md:right-auto md:flex md:border-0 md:pt-0"><HeroFact value="1,250+" label="verified homes"/><HeroFact value="23 days" label="avg. time to match"/><HeroFact value="4.9/5" label="from local buyers"/></div></div></section>

    <section className="page-shell pt-24"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">{words.featured}</p><h2 className="section-title">{words.featuredTitle}</h2></div><Link href={`/${locale}/properties`} className="outline-button">{words.browse}<ArrowRight size={16}/></Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{properties.slice(0,3).map((property,index)=><motion.div key={property.id} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{delay:index*.08}}><PropertyCard property={property} locale={locale}/></motion.div>)}</div></section>

    <section className="page-shell pt-24"><div className="grid gap-8 lg:grid-cols-[.88fr_1.12fr]"><div className="relative min-h-[340px] overflow-hidden rounded-3xl bg-ink p-8 text-white md:p-10"><div className="absolute -right-10 -top-12 h-56 w-56 rounded-full bg-gold/25 blur-3xl"/><p className="eyebrow relative">Designed for confidence</p><h2 className="relative mt-3 max-w-sm font-serif text-4xl leading-tight md:text-5xl">More signal. Less searching.</h2><p className="relative mt-5 max-w-md leading-7 text-slate-300">From verified details to a genuinely useful compare view, everything is designed to make your next decision feel clear.</p><Link href={`/${locale}/properties`} className="relative mt-8 inline-flex items-center gap-2 text-sm font-bold text-gold">See how it works <ArrowRight size={16}/></Link></div><div className="grid gap-4 sm:grid-cols-2"><Reason icon={<CheckCircle2/>} title="Every listing checked" copy="Meaningful listing details, transparent badges, and a tighter standard for live homes."/><Reason icon={<TrendingUp/>} title="Local intelligence" copy="Neighbourhood context, price signals, and market insights where you need them."/><Reason icon={<Landmark/>} title="Made to compare" copy="See the details side-by-side before you decide what deserves a visit."/><Reason icon={<MapPin/>} title="Search your way" copy="Switch between a considered grid and a map built around your chosen area."/></div></div></section>

    <section className="page-shell pt-24"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">Explore by neighbourhood</p><h2 className="section-title">The city, closer.</h2></div><Link href={`/${locale}/properties`} className="hidden items-center gap-1 text-sm font-bold text-ink hover:text-gold sm:flex dark:text-white">View all localities <ChevronRight size={16}/></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{cityHighlights.map((city, index)=><motion.div initial={{opacity:0,scale:.98}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} transition={{delay:index*.07}} key={city.name}><Link href={`/${locale}/properties?q=${city.name}`} className="image-shine group relative block aspect-[1.24/1] overflow-hidden rounded-3xl"><Image src={city.image} alt={city.name} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute bottom-5 left-5 z-10"><p className="font-serif text-2xl font-bold text-white">{city.name}</p><p className="mt-1 text-sm text-white/75">{city.count} to explore</p></div></Link></motion.div>)}</div></section>

    <section className="page-shell pt-24"><div className="relative overflow-hidden rounded-3xl bg-[#e5ede7] px-7 py-11 dark:bg-[#173128] md:px-12"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_top_right,rgba(212,169,79,.45),transparent_55%)]"/><div className="relative max-w-2xl"><p className="eyebrow">Own a place?</p><h2 className="mt-3 font-serif text-4xl text-ink dark:text-white md:text-5xl">Let the right people find it.</h2><p className="mt-4 max-w-xl leading-7 text-slate-600 dark:text-slate-300">Create a listing that does justice to your space, manage real enquiries, and see exactly how it’s performing.</p><Link href={`/${locale}/broker`} className="gold-button mt-7">List a property <ArrowRight size={17}/></Link></div></div></section>
  </main>;
}

function HeroFact({ value, label }: { value: string; label: string }) { return <div className="min-w-[114px]"><p className="font-serif text-xl font-bold">{value}</p><p className="mt-0.5 text-[11px] text-white/60">{label}</p></div>; }
function Reason({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="surface p-6 transition hover:shadow-soft"><span className="grid h-10 w-10 place-items-center rounded-xl bg-gold/15 text-gold">{icon}</span><h3 className="mt-5 font-serif text-xl font-bold text-ink dark:text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{copy}</p></div>; }
