import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Clock3, TrendingUp } from 'lucide-react';

const articles = [
  {title:'Gurugram’s 2026 rental market: where value is moving',category:'Market guide',time:'6 min read',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80'},
  {title:'How to read a neighbourhood before you buy',category:'Buying smarter',time:'4 min read',image:'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=1400&q=80'},
  {title:'What serious renters notice first in a listing',category:'For professionals',time:'5 min read',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=80'}
];
export function InsightsExperience({locale}:{locale:string}) { return <main className="page-shell py-9 md:py-14"><section className="rounded-3xl bg-ink px-7 py-14 text-white md:px-12 md:py-20"><p className="eyebrow">EstateHub insights</p><h1 className="mt-4 max-w-3xl font-serif text-5xl font-bold leading-[.98] md:text-7xl">A more useful view of your local market.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-300">Signal over noise: neighbourhood knowledge, practical buying advice, and what the numbers mean for your next move.</p></section><section className="mt-16"><div className="flex items-end justify-between"><div><p className="eyebrow">Featured reading</p><h2 className="section-title">What’s shaping the city.</h2></div><TrendingUp className="text-gold"/></div><div className="mt-9 grid gap-6 md:grid-cols-3">{articles.map((article,index)=><article className={`group ${index===0?'md:col-span-2 md:grid md:grid-cols-2':''} surface overflow-hidden`} key={article.title}><div className={`relative overflow-hidden ${index===0?'min-h-64':'aspect-[1.35/1]'}`}><Image src={article.image} alt="" fill className="object-cover transition duration-700 group-hover:scale-105"/></div><div className="flex flex-col p-6"><p className="text-xs font-bold uppercase tracking-[.13em] text-gold">{article.category}</p><h3 className="mt-3 font-serif text-2xl font-bold leading-tight text-ink dark:text-white">{article.title}</h3><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><Clock3 size={14}/>{article.time}</div><Link href={`/${locale}/insights`} className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-ink hover:text-gold dark:text-white">Read article <ArrowRight size={15}/></Link></div></article>)}</div></section><section className="mt-16 rounded-3xl bg-[#e5ede7] p-8 dark:bg-[#173128] md:p-10"><div className="max-w-2xl"><p className="eyebrow">A monthly dispatch</p><h2 className="mt-3 font-serif text-4xl font-bold text-ink dark:text-white">Better local intelligence, in your inbox.</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">One thoughtful email on price movement, new neighbourhoods and the stories behind local spaces.</p><div className="mt-6 flex max-w-md gap-2"><input className="input-surface flex-1" placeholder="Your email"/><button className="gold-button">Subscribe</button></div></div></section></main>; }
