'use client';

import { useMemo, useState } from 'react';
import { Filter, Grid2X2, ListFilter, Map, MapPin, SlidersHorizontal, X } from 'lucide-react';
import { properties } from '@/lib/data';
import { PropertyCard, PropertySkeleton } from './property-card';
import { motion, AnimatePresence } from 'framer-motion';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';

const categories = ['All', 'Apartment', 'Villa', 'Commercial', 'Plot', 'PG'];

export function ListingsExperience({ locale }: { locale: string }) {
  const params = useSearchParams(); const initialPurpose = params.get('purpose') === 'rent' ? 'rent' : params.get('purpose') === 'sale' ? 'sale' : 'all';
  const [purpose, setPurpose] = useState(initialPurpose); const [category, setCategory] = useState('All'); const [beds, setBeds] = useState('Any'); const [furnishing, setFurnishing] = useState('Any'); const [sort, setSort] = useState('newest'); const [mapView, setMapView] = useState(false); const [filtersOpen,setFiltersOpen] = useState(false); const [loading,setLoading] = useState(false); const [compareIds,setCompareIds] = useState<string[]>([]); const [compareNote,setCompareNote] = useState('');
  const results = useMemo(() => { let selected = properties.filter((p) => (purpose === 'all' || p.purpose === purpose) && (category === 'All' || p.category === category) && (beds === 'Any' || p.beds >= Number(beds)) && (furnishing === 'Any' || p.furnishing === furnishing)); if(sort === 'low') selected = [...selected].sort((a,b)=>a.price-b.price); if(sort === 'high') selected = [...selected].sort((a,b)=>b.price-a.price); if(sort === 'views') selected = [...selected].sort((a,b)=>b.views-a.views); return selected; },[purpose,category,beds,furnishing,sort]);
  const reset = () => { setPurpose('all'); setCategory('All'); setBeds('Any'); setFurnishing('Any'); setSort('newest'); };
  const triggerFilters = () => { setLoading(true); setTimeout(()=>setLoading(false),450); };
  const toggleCompare = (id: string) => { if (compareIds.includes(id)) { setCompareIds(items=>items.filter(item=>item!==id)); return; } if (compareIds.length === 3) { setCompareNote('Choose up to three homes to compare.'); setTimeout(()=>setCompareNote(''),2200); return; } setCompareIds(items=>[...items,id]); };
  return <main className="page-shell py-8 md:py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Explore properties</p><h1 className="section-title">Make your next move.</h1><p className="mt-3 text-sm text-slate-500 dark:text-slate-400">{results.length} places curated around Gurugram</p></div><div className="flex rounded-xl border border-slate-200 bg-white p-1 dark:border-white/10 dark:bg-white/5"><button onClick={()=>setMapView(false)} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${!mapView ? 'bg-ink text-white dark:bg-gold dark:text-ink' : 'text-slate-500 dark:text-slate-300'}`}><Grid2X2 size={15}/> Grid</button><button onClick={()=>setMapView(true)} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${mapView ? 'bg-ink text-white dark:bg-gold dark:text-ink' : 'text-slate-500 dark:text-slate-300'}`}><Map size={15}/> Map</button></div></div>
    <div className="mt-8 flex items-center gap-2 overflow-x-auto pb-2 hide-scrollbar"><button onClick={()=>setFiltersOpen(true)} className="outline-button shrink-0"><SlidersHorizontal size={16}/> Filters</button><button onClick={()=>{setPurpose(purpose==='sale'?'all':'sale');triggerFilters();}} className={`shrink-0 rounded-xl border px-3.5 py-2.5 text-xs font-bold ${purpose==='sale'?'border-gold bg-gold/15 text-ink dark:text-gold':'border-slate-200 bg-white text-slate-600 dark:border-white/10 dark:bg-white/5 dark:text-slate-300'}`}>Buy</button><button onClick={()=>{setPurpose(purpose==='rent'?'all':'rent');triggerFilters();}} className={`shrink-0 rounded-xl border px-3.5 py-2.5 text-xs font-bold ${purpose==='rent'?'border-gold bg-gold/15 text-ink dark:text-gold':'border-slate-200 bg-white text-slate-600 dark:border-white/10 dark:bg-white/5 dark:text-slate-300'}`}>Rent</button>{categories.slice(1).map(item=><button onClick={()=>{setCategory(category===item?'All':item);triggerFilters();}} className={`shrink-0 rounded-xl border px-3.5 py-2.5 text-xs font-bold ${category===item?'border-gold bg-gold/15 text-ink dark:text-gold':'border-slate-200 bg-white text-slate-600 dark:border-white/10 dark:bg-white/5 dark:text-slate-300'}`} key={item}>{item}</button>)}<button onClick={reset} className="shrink-0 px-2 text-xs font-bold text-slate-500 hover:text-ink dark:hover:text-white">Reset</button></div>
    <div className={`mt-6 grid gap-6 ${mapView ? 'xl:grid-cols-[minmax(0,1fr)_420px]' : ''}`}><section><div className="mb-5 flex items-center justify-between"><p className="text-sm font-semibold text-slate-600 dark:text-slate-300"><ListFilter className="mr-1.5 inline" size={16}/>{results.length} properties found</p><label className="flex items-center gap-2 text-xs font-semibold text-slate-500">Sort<select value={sort} onChange={e=>setSort(e.target.value)} className="input-surface py-2 text-xs"><option value="newest">Newest</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="views">Most viewed</option></select></label></div><div className={`grid gap-5 ${mapView ? 'md:grid-cols-2' : 'md:grid-cols-2 xl:grid-cols-3'}`}>{loading ? Array.from({length:6}).map((_,i)=><PropertySkeleton key={i}/>) : results.map(p=><PropertyCard key={p.id} property={p} locale={locale} compareSelected={compareIds.includes(p.id)} onToggleCompare={()=>toggleCompare(p.id)}/>)}</div>{!loading && !results.length && <div className="surface py-20 text-center"><Filter className="mx-auto text-gold"/><p className="mt-4 font-serif text-2xl font-bold text-ink dark:text-white">No homes match just yet.</p><button onClick={reset} className="gold-button mt-5">Clear filters</button></div>}</section>{mapView && <MapPanel results={results}/>}</div>
    <AnimatePresence>{filtersOpen && <FilterPanel category={category} setCategory={setCategory} beds={beds} setBeds={setBeds} furnishing={furnishing} setFurnishing={setFurnishing} close={()=>setFiltersOpen(false)} apply={()=>{triggerFilters();setFiltersOpen(false);}} reset={reset}/>}</AnimatePresence>
    <AnimatePresence>{compareIds.length>0&&<motion.div initial={{y:90,opacity:0}} animate={{y:0,opacity:1}} exit={{y:90,opacity:0}} className="fixed bottom-5 left-1/2 z-40 flex w-[calc(100%-2.5rem)] max-w-lg -translate-x-1/2 items-center justify-between rounded-2xl bg-ink p-3 pl-5 text-white shadow-float"><div><p className="text-sm font-bold">{compareIds.length} home{compareIds.length>1?'s':''} selected</p><p className="text-xs text-slate-400">Compare up to three side-by-side</p></div><Link href={`/${locale}/compare?ids=${compareIds.join(',')}`} className="gold-button px-4 py-2.5">Compare</Link></motion.div>}</AnimatePresence>{compareNote&&<div className="fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white shadow-float">{compareNote}</div>}
  </main>;
}

function MapPanel({ results }: { results: typeof properties }) { return <aside className="sticky top-24 h-[590px] overflow-hidden rounded-3xl bg-[#dce6df] dark:bg-[#1a3235]"><div className="absolute inset-0 opacity-35" style={{backgroundImage:'linear-gradient(#8fa5a0 1px, transparent 1px), linear-gradient(90deg, #8fa5a0 1px, transparent 1px)',backgroundSize:'46px 46px'}}/><div className="absolute left-[12%] top-0 h-full w-12 rotate-[15deg] bg-white/50"/><div className="absolute left-0 top-[44%] h-8 w-full -rotate-[6deg] bg-white/55"/><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_60%_30%,transparent_0%,rgba(10,35,40,.1)_100%)]"/><div className="absolute left-5 top-5 rounded-xl bg-white px-3 py-2 text-xs font-bold text-ink shadow-lg dark:bg-ink dark:text-white">{results.length} homes in view</div>{results.map((property,i)=><button title={property.title} key={property.id} style={{left:`${15+(i*23)%65}%`,top:`${24+(i*17)%58}%`}} className="absolute z-10 grid h-9 w-9 place-items-center rounded-full border-2 border-white bg-gold text-ink shadow-lg transition hover:scale-110"><MapPin size={17} fill="currentColor"/></button>)}<div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-ink/90 p-4 text-white backdrop-blur"><p className="text-xs text-gold">Map explorer</p><p className="mt-1 text-sm font-semibold">Pins cluster intelligently as you browse an area.</p></div></aside>; }
function FilterPanel({ category,setCategory,beds,setBeds,furnishing,setFurnishing,close,apply,reset }: { category:string;setCategory:(v:string)=>void;beds:string;setBeds:(v:string)=>void;furnishing:string;setFurnishing:(v:string)=>void;close:()=>void;apply:()=>void;reset:()=>void; }) { return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] bg-ink/45 backdrop-blur-sm"><motion.aside initial={{x:430}} animate={{x:0}} exit={{x:430}} transition={{type:'spring',damping:28,stiffness:300}} className="ml-auto flex h-full w-full max-w-md flex-col bg-white p-6 dark:bg-[#142126]"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl font-bold text-ink dark:text-white">Fine tune your search</h2><button onClick={close} className="rounded-full p-2 hover:bg-slate-100 dark:hover:bg-white/10"><X size={19}/></button></div><div className="mt-8 space-y-7 overflow-y-auto pr-1"><FilterGroup label="Property type"><div className="flex flex-wrap gap-2">{categories.map(item=><button key={item} onClick={()=>setCategory(item)} className={`rounded-xl border px-3 py-2 text-xs font-bold ${category===item?'border-gold bg-gold/15 text-ink dark:text-gold':'border-slate-200 text-slate-500 dark:border-white/10 dark:text-slate-300'}`}>{item}</button>)}</div></FilterGroup><FilterGroup label="Budget"><div className="grid grid-cols-2 gap-3"><input className="input-surface" placeholder="Min price"/><input className="input-surface" placeholder="Max price"/></div></FilterGroup><FilterGroup label="Bedrooms"><div className="flex gap-2">{['Any','1','2','3','4'].map(item=><button key={item} onClick={()=>setBeds(item)} className={`grid h-10 w-12 place-items-center rounded-xl border text-xs font-bold ${beds===item?'border-gold bg-gold/15 text-ink dark:text-gold':'border-slate-200 text-slate-500 dark:border-white/10 dark:text-slate-300'}`}>{item==='Any'?'Any':item+'+'}</button>)}</div></FilterGroup><FilterGroup label="Furnishing"><div className="space-y-2">{['Any','Furnished','Semi-furnished','Unfurnished'].map(item=><label key={item} className="flex items-center gap-3 text-sm text-slate-600 dark:text-slate-300"><input type="radio" checked={furnishing===item} onChange={()=>setFurnishing(item)} className="accent-gold"/> {item}</label>)}</div></FilterGroup><FilterGroup label="Amenities"><div className="grid grid-cols-2 gap-3">{['Pool','Gym','Parking','Lift','Pet friendly','Power backup'].map(item=><label key={item} className="flex items-center gap-2 text-sm text-slate-600 dark:text-slate-300"><input type="checkbox" className="accent-gold"/> {item}</label>)}</div></FilterGroup></div><div className="mt-6 flex gap-3 border-t border-slate-100 pt-5 dark:border-white/10"><button onClick={reset} className="outline-button flex-1">Reset</button><button onClick={apply} className="gold-button flex-[1.3]">Show homes</button></div></motion.aside></motion.div>; }
function FilterGroup({ label, children }: { label:string;children:React.ReactNode }) { return <div><p className="mb-3 text-xs font-bold uppercase tracking-[.15em] text-ink dark:text-white">{label}</p>{children}</div>; }
