'use client';

import Image from 'next/image';
import Link from 'next/link';
import { Bath, BedDouble, Heart, MapPin, Maximize2, ShieldCheck } from 'lucide-react';
import { Property } from '@/lib/data';
import { useState } from 'react';

export function PropertyCard({ property, locale = 'en', compact = false, compareSelected = false, onToggleCompare }: { property: Property; locale?: string; compact?: boolean; compareSelected?: boolean; onToggleCompare?: (property: Property) => void }) {
  const [saved, setSaved] = useState(false);
  return <article className={`group overflow-hidden ${compact ? '' : 'surface'} transition hover:-translate-y-1 hover:shadow-soft`}><Link href={`/${locale}/properties/${property.slug}`} className="image-shine relative block aspect-[1.24/1] overflow-hidden bg-slate-200"><Image src={property.image} alt={property.title} fill sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105"/>{property.featured && <span className="absolute left-3 top-3 z-10 rounded-full bg-gold px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider text-ink">Featured</span>}<span className="absolute bottom-3 left-3 z-10 flex items-center gap-1 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold text-ink backdrop-blur"><MapPin size={11}/>{property.locality}</span></Link><div className="p-4"><div className="flex items-start justify-between gap-3"><Link href={`/${locale}/properties/${property.slug}`}><h3 className="font-serif text-xl font-bold text-ink dark:text-white">{property.title}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{property.locality}, {property.city}</p></Link><button aria-label="Save listing" onClick={() => setSaved(!saved)} className={`rounded-full p-2 transition ${saved ? 'bg-rose-50 text-rose-500' : 'text-slate-400 hover:bg-slate-100 dark:hover:bg-white/10'}`}><Heart size={18} fill={saved ? 'currentColor' : 'none'}/></button></div><div className="mt-4 flex items-center justify-between"><p className="text-lg font-bold text-ink dark:text-white">{property.priceLabel}</p>{property.verified && <span className="flex items-center gap-1 text-[11px] font-bold text-moss dark:text-[#87c59f]"><ShieldCheck size={14}/> Verified</span>}</div><div className="mt-4 flex border-t border-slate-100 pt-3 text-xs font-semibold text-slate-500 dark:border-white/10 dark:text-slate-400"><span className="flex items-center gap-1.5 pr-3"><BedDouble size={15}/>{property.beds || '—'} Beds</span><span className="flex items-center gap-1.5 border-l border-slate-100 px-3 dark:border-white/10"><Bath size={15}/>{property.baths} Baths</span><span className="flex items-center gap-1.5 border-l border-slate-100 pl-3 dark:border-white/10"><Maximize2 size={14}/>{property.area.toLocaleString()} ft²</span></div>{onToggleCompare && <button onClick={() => onToggleCompare(property)} className={`mt-4 w-full rounded-lg py-2 text-xs font-bold transition ${compareSelected ? 'bg-gold text-ink' : 'bg-slate-100 text-slate-600 hover:bg-gold/15 dark:bg-white/10 dark:text-slate-300'}`}>{compareSelected ? 'Added to comparison' : 'Compare this home'}</button>}</div></article>;
}

export function PropertySkeleton() { return <div className="surface overflow-hidden"><div className="skeleton aspect-[1.24/1]"/><div className="space-y-3 p-4"><div className="skeleton h-5 w-2/3 rounded"/><div className="skeleton h-3 w-1/2 rounded"/><div className="skeleton h-4 w-1/3 rounded"/></div></div>; }
