'use client';

import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowRight, Building2, ChevronDown, Heart, Menu, Moon, Search, Sun, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { t } from '@/lib/i18n';

const propertyGroups = [
  { label: 'Residential', items: ['Apartments', 'Villas', 'Independent floors'] },
  { label: 'Commercial', items: ['Office spaces', 'Retail', 'Coworking'] },
  { label: 'PG / Rental', items: ['PGs', 'Shared homes', 'Short stays'] },
  { label: 'Land & Plots', items: ['Residential plots', 'Farm land', 'Industrial'] }
];

export function Mark() {
  return <Link href="/en" className="group flex items-center gap-2.5" aria-label="EstateHub home"><span className="grid h-9 w-9 place-items-center rounded-xl bg-navy text-gold shadow-lg shadow-navy/15"><Building2 size={19} strokeWidth={2.3} /></span><span className="font-serif text-2xl font-bold tracking-tight text-ink dark:text-white">Estate<span className="text-gold">Hub</span></span></Link>;
}

export function SiteHeader({ locale }: { locale: string }) {
  const [open, setOpen] = useState(false); const [menu, setMenu] = useState(false); const [dark, setDark] = useState(false); const [query, setQuery] = useState('');
  const router = useRouter(); const pathname = usePathname(); const words = t(locale);
  useEffect(() => { const setting = localStorage.getItem('estatehub-theme'); const next = setting === 'dark' || (!setting && window.matchMedia('(prefers-color-scheme: dark)').matches); setDark(next); document.body.classList.toggle('dark', next); }, []);
  const toggleTheme = () => { const next = !dark; setDark(next); document.body.classList.toggle('dark', next); localStorage.setItem('estatehub-theme', next ? 'dark' : 'light'); };
  const changeLocale = (next: string) => { document.cookie = `estatehub-locale=${next}; path=/; max-age=31536000`; router.push(pathname.replace(/^\/(en|hi)/, `/${next}`)); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); router.push(`/${locale}/properties${query ? `?q=${encodeURIComponent(query)}` : ''}`); setOpen(false); };
  return <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-pearl/85 backdrop-blur-xl dark:border-white/10 dark:bg-[#0d171b]/85">
    <div className="page-shell flex h-[74px] items-center justify-between gap-4"><Mark />
      <nav className="hidden items-center gap-7 lg:flex"><button onClick={() => setMenu(!menu)} className="flex items-center gap-1 text-sm font-semibold text-ink transition hover:text-gold dark:text-white">Properties <ChevronDown size={15} className={menu ? 'rotate-180 transition' : 'transition'} /></button><Link href={`/${locale}/properties`} className="text-sm font-semibold text-ink transition hover:text-gold dark:text-white">Explore</Link><Link href={`/${locale}/list-property`} className="text-sm font-semibold text-ink transition hover:text-gold dark:text-white">List property</Link><Link href={`/${locale}/broker`} className="text-sm font-semibold text-ink transition hover:text-gold dark:text-white">For professionals</Link><Link href={`/${locale}/insights`} className="text-sm font-semibold text-ink transition hover:text-gold dark:text-white">Insights</Link></nav>
      <div className="flex items-center gap-2"><button aria-label="Search" onClick={() => setOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl text-ink transition hover:bg-white dark:text-white dark:hover:bg-white/10"><Search size={19}/></button><button aria-label="Toggle color mode" onClick={toggleTheme} className="grid h-10 w-10 place-items-center rounded-xl text-ink transition hover:bg-white dark:text-white dark:hover:bg-white/10">{dark ? <Sun size={18}/> : <Moon size={18}/>}</button><select aria-label="Change language" value={locale} onChange={(e) => changeLocale(e.target.value)} className="hidden cursor-pointer bg-transparent text-xs font-bold text-ink outline-none dark:text-white sm:block"><option value="en">EN</option><option value="hi">हिंदी</option></select><Link href={`/${locale}/login`} className="hidden rounded-xl bg-ink px-4 py-2.5 text-sm font-bold text-white transition hover:bg-navy md:block dark:bg-gold dark:text-ink">{words.login}</Link><button onClick={() => setOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl bg-ink text-white lg:hidden"><Menu size={19}/></button></div>
    </div>
    <AnimatePresence>{menu && <motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} className="absolute inset-x-0 top-[74px] hidden border-b border-slate-200 bg-white shadow-float dark:border-white/10 dark:bg-[#142126] lg:block"><div className="page-shell grid grid-cols-4 gap-8 py-8">{propertyGroups.map((group) => <div key={group.label}><p className="mb-3 text-xs font-bold uppercase tracking-[.15em] text-gold">{group.label}</p>{group.items.map((item) => <Link onClick={() => setMenu(false)} key={item} href={`/${locale}/properties`} className="block py-1.5 text-sm text-slate-600 hover:text-ink dark:text-slate-300 dark:hover:text-gold">{item}</Link>)}</div>)}<div className="rounded-2xl bg-[#eef3ef] p-5 dark:bg-white/5"><p className="font-serif text-lg text-ink dark:text-white">Looking to sell?</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Reach serious buyers with a better listing.</p><Link href={`/${locale}/broker`} className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-gold">Start listing <ArrowRight size={15}/></Link></div></div></motion.div>}</AnimatePresence>
    <AnimatePresence>{open && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[60] bg-ink/55 p-5 backdrop-blur-sm"><motion.div initial={{y:-25,scale:.98}} animate={{y:0,scale:1}} exit={{y:-25,scale:.98}} className="mx-auto mt-20 max-w-2xl rounded-3xl bg-white p-5 shadow-float dark:bg-[#142126]"><div className="mb-5 flex items-center justify-between"><div><p className="font-serif text-2xl font-bold text-ink dark:text-white">Where are you looking?</p><p className="mt-1 text-sm text-slate-500">Find homes by locality, landmark, or project.</p></div><button onClick={() => setOpen(false)} className="rounded-full p-2 hover:bg-slate-100 dark:hover:bg-white/10"><X size={20}/></button></div><form onSubmit={submit} className="flex gap-2"><input autoFocus value={query} onChange={(e)=>setQuery(e.target.value)} className="input-surface flex-1" placeholder={words.search}/><button className="gold-button px-4"><Search size={18}/></button></form><div className="mt-5 flex flex-wrap gap-2">{['Golf Course Road','DLF Phase 4','Sector 43','Cyber City'].map((place) => <button onClick={() => {setQuery(place);}} key={place} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600 hover:bg-gold/20 dark:bg-white/10 dark:text-slate-300">{place}</button>)}</div><div className="mt-6 border-t border-slate-100 pt-4 dark:border-white/10"><Link href={`/${locale}/dashboard`} className="flex items-center gap-2 text-sm font-semibold text-ink dark:text-white"><Heart size={16} className="text-gold"/> Your saved homes and searches</Link></div></motion.div></motion.div>}</AnimatePresence>
  </header>;
}

export function Footer({ locale }: { locale: string }) {
  return <footer className="mt-20 bg-ink text-white"><div className="page-shell grid gap-12 py-14 md:grid-cols-[1.4fr_repeat(3,1fr)]"><div><Mark/><p className="mt-5 max-w-sm text-sm leading-6 text-slate-400">The considered way to discover, compare and list exceptional places in your city.</p><div className="mt-6 flex gap-3"><span className="rounded-full border border-white/15 px-3 py-1 text-xs text-slate-300">Made for {locale === 'hi' ? 'भारत' : 'India'}</span><span className="rounded-full border border-white/15 px-3 py-1 text-xs text-slate-300">Verified listings</span></div></div>{[['Explore',['Buy a home','Rent a home','New projects','Localities']],['Professionals',['List a property','Broker dashboard','Pricing','Partner with us']],['Company',['About EstateHub','Insights','Contact','Trust & safety']]].map(([name, links])=><div key={String(name)}><p className="text-sm font-bold">{name}</p><div className="mt-4 space-y-2.5">{(links as string[]).map(link=><Link key={link} href={`/${locale}/properties`} className="block text-sm text-slate-400 transition hover:text-gold">{link}</Link>)}</div></div>)}</div><div className="border-t border-white/10"><div className="page-shell flex flex-col justify-between gap-3 py-5 text-xs text-slate-500 sm:flex-row"><p>© 2026 EstateHub. All rights reserved.</p><p>Privacy · Terms · Accessibility</p></div></div></footer>;
}
